### ISSUE TITLE
Maybe compile the release binares with size optimisations + LTO

### ISSUE THREAD

**Issue by ejpcmac** [ejpcmac/rust-template#12]
## Rationale

The release binaries should be as tiny as possible to ease the distribution. Setting the following reduces the size significantly:

```toml
[profile.release]
strip = true
otp-level = "s"
lto = true
codegen-units = 1
```

## Important things to consider

* LTO increases the link time **a lot**
* The CI checking the packages should ideally not be impacted by the change, only the release flow
* The Nix package, which can be built on user’s machines and even sometimes used directly in the devshell, should ideally not take a long time to build
